accounts:
  - name: alice
    coins: [ "200000000stake" ]
    mnemonic: "invite velvet shuffle day shed ramp page business index curve voice question crunch fence pepper olive honey train volcano crime very oil saddle average"
  - name: bob
    coins: [ "200000000stake" ]
    mnemonic: "fork edit oil vacant town valid hard pepper square push pear scale story twenty bleak captain egg figure smile witness throw aware effort transfer"
  - name: carol
    coins: [ "200000000stake" ]
    mnemonic: "amount enable repeat velvet horror dutch truth nuclear stand minute mistake enjoy twice wife sheriff throw sauce unfair stamp chaos antique bread work author"
validator:
  name: alice
  staked: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: [ "5token", "100000stake" ]
  port: 4502
host:
  rpc: ":26659"
  p2p: ":26658"
  prof: ":6061"
  grpc: ":9092"
  grpc-web: ":9093"
  api: ":1318"